import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  pt: {
    'app.title': 'Shopee RTS Control Tower',
    'app.tab.operacional': 'Dashboard Operacional',
    'app.tab.executiva': 'Visão Executiva',
    'app.tab.relatorio': 'Relatório Estratégico',
    'app.lastUpdate': 'Última atualização:',
    'app.loading': 'Carregando dados...',
    'app.error': 'Erro ao carregar dados',
    'app.uploadCsv': 'Fazer Upload de CSV',
    'app.tryAgain': 'Tentar Novamente',
    'app.corsError': 'O Google Sheets bloqueou o acesso direto devido a políticas de CORS.',
    'app.corsSolution': 'Para visualizar os dados, faça o download da planilha como CSV e faça o upload abaixo:',
    'app.downloadCsv': '1. Baixar CSV do Google Sheets',
    'app.selectFile': '2. Selecionar arquivo baixado',
    
    'op.station': 'Estação',
    'op.responsability': 'Responsável',
    'op.stuckAging': 'Stuck Aging',
    'op.sinceDropAging': 'Since Drop Aging',
    'op.totalShipments': 'Total Shipments',
    'op.clickToViewAll': 'Clique para ver todos',
    'op.avgDaysStation': 'Média Dias na Estação',
    'op.days': 'dias',
    'op.clickToViewAboveAvg': 'Clique para ver acima da média',
    'op.percentStuck': '% Stuck >5 dias',
    'op.clickToViewCases': 'Clique para ver os {count} casos',
    'op.critical20': 'Críticos >20 dias',
    'op.clickToDetailCritical': 'Clique para detalhar críticos',
    'op.volByResp': 'Volume por Responsável',
    'op.agingInStation': 'Aging em Estação',
    'op.distRtsDays': 'Distribuição Dias RTS (Histograma)',
    'op.rtsMonitoring': 'Monitoramento RTS',
    'op.shipmentId': 'Shipment ID',
    'op.daysInStation': 'Dias na Estação',
    'op.rtsDays': 'Dias RTS',
    'op.stuckDays': 'Dias Stuck',
    'op.noRecords': 'Nenhum registro encontrado.',
    'op.showing': 'Mostrando {start} a {end} de {total} registros',
    'op.prev': 'Anterior',
    'op.next': 'Próxima',
    'op.allShipments': 'Todos os Shipments',
    'op.aboveAvg': 'Acima da Média na Estação (> {avg} dias)',
    'op.stuck5': 'Stuck > 5 dias',
    'op.criticalRts': 'Críticos > 20 dias (RTS)',
    'op.clearFilter': 'Limpar Filtro KPI',

    'exec.distRtsAging': 'Distribuição RTS Aging',
    'exec.top10Critical': 'Top 10 Estações Críticas (>10 dias)',
    'exec.execSummary': 'RESUMO EXECUTIVO',
    'exec.currentBase': 'Base atual:',
    'exec.openShipments': 'envios em aberto',
    'exec.stuckMoreThan5': 'estão com mais de 5 dias de stuck',
    'exec.casesExceed20': 'casos ultrapassam 20 dias',
    'exec.recommendation': 'Recomenda-se ação imediata nas estações com média superior a 10 dias.',
    'exec.spxStatusVol': 'Status SPX (Volume)',
    'exec.spxStatusPct': 'Status SPX (%)',
    'exec.grandTotal': 'Grand Total',
    'exec.showMore': 'Ver Mais ({count})',
    'exec.showLess': 'Ver Menos',
    'exec.topSpxStatus': 'O status SPX mais frequente é',
    'exec.representing': 'representando',
    'exec.ofTotalVolume': 'do volume total',

    'rel.filterOpType': 'Filtrar por Tipo de Operação',
    'rel.searchOp': 'Buscar operação (ex: SOC, HUB)...',
    'rel.noOpFound': 'Nenhuma operação encontrada',
    'rel.showingAll': 'Exibindo todas as operações.',
    'rel.stationsSelected': '{count} estação(ões) selecionada(s).',
    'rel.exportPdf': 'Exportar PDF',
    'rel.to': 'PARA:',
    'rel.toValue': 'Diretoria de Operações / Gerência de Supply Chain',
    'rel.from': 'DE:',
    'rel.fromValue': 'Engenharia de Inteligência de Logística Reversa',
    'rel.subject': 'ASSUNTO:',
    'rel.subjectValue': 'Relatório Estratégico de Performance e Recuperação de Ativos',
    'rel.date': 'DATA:',
    'rel.sec1': '1. Resumo Executivo',
    'rel.p1_1': 'O cenário atual da operação de logística reversa ',
    'rel.p1_focus': '(foco em {tags}) ',
    'rel.p1_2': 'apresenta um estado que requer atenção imediata. Com um volume de ',
    'rel.p1_3': ' itens',
    'rel.p1_4': ' retidos no fluxo, a ineficiência operacional é evidenciada pelo Aging Médio que atingiu ',
    'rel.p1_5': ' dias',
    'rel.p1_6': ' de retenção desde o RTS.',
    'rel.p2_1': 'A operação registra ',
    'rel.p2_2': '% de descumprimento de SLA',
    'rel.p2_3': ' (itens com mais de 30 dias), e a totalidade destes itens é classificada como Risco Alto. Estes dados indicam que os produtos estão, na prática, paralisados no fluxo ou retidos por questões burocráticas/processuais severas, resultando em depreciação do ativo e custo de oportunidade elevado para a companhia.',
    'rel.sec2': '2. Diagnóstico Técnico',
    'rel.sec2_desc': 'A análise detalhada aponta para gargalos específicos no processo macro de devolução. As tabelas abaixo detalham as localizações mais críticas e os responsáveis com maior tempo de retenção.',
    'rel.analysisLoc': 'Análise por Localização (Gargalos Regionais - Top 5)',
    'rel.location': 'Localização',
    'rel.volItems': 'Volume (Itens)',
    'rel.avgAgingDays': 'Aging Médio (Dias)',
    'rel.critStatus': 'Status de Criticidade',
    'rel.critical': 'Crítico',
    'rel.warning': 'Atenção',
    'rel.noData': 'Sem dados para exibir',
    'rel.analysisResp': 'Análise por Responsabilidade',
    'rel.analysisRespDesc': 'A responsabilidade está distribuída, mas os seguintes setores detêm os maiores tempos de retenção, indicando falhas na última milha da reversa e na triagem de entrada.',
    'rel.responsible': 'Responsável',
    'rel.volume': 'Volume',
    'rel.processImpact': 'Impacto no Processo',
    'rel.impact1': 'Falha na coleta/devolução física',
    'rel.impact2': 'Falha na conferência/inventário',
    'rel.impact3': 'Atraso no processo/disputa',
    'rel.engObs': 'Observação de Engenharia:',
    'rel.engObsDesc': 'Um aging superior a 30 dias em grande parte da amostra indica que estes itens podem ter sofrido sinistros não baixados no sistema ou estão em "limbo" administrativo entre as transferências de custódia.',
    'rel.analysisSpx': 'Análise por Status SPX',
    'rel.analysisSpxDesc': 'A distribuição dos status SPX revela os principais gargalos sistêmicos e operacionais no fluxo da logística reversa.',
    'rel.spxStatus': 'Status SPX',
    'rel.spxPercentage': 'Representatividade',
    'rel.spxInsight': 'O status {status} concentra a maior parte do volume ({percentage}), exigindo priorização no destravamento sistêmico e físico.',
    'rel.sec3': '3. Recomendações Práticas',
    'rel.sec3_desc': 'Para reverter o quadro de estagnação e evitar o agravamento do prejuízo, as seguintes ações devem ser executadas imediatamente:',
    'rel.rec1_title': 'Força-Tarefa de Saneamento (Write-off ou Recuperação):',
    'rel.rec1_desc': ' Devido ao aging elevado, a probabilidade de integridade física dos itens mais antigos é baixa. Recomendo a auditoria física imediata nas localidades mais críticas apontadas acima. Caso os itens não sejam localizados em 48h, proceder com o write-off (baixa contábil) e acionamento de seguro ou penalização dos responsáveis.',
    'rel.rec2_title': 'Revisão do Fluxo de Escalonamento:',
    'rel.rec2_desc': ' O fato de uma parcela significativa dos itens estar fora do SLA e ser de Risco Alto sem intervenção prévia demonstra falha nos alertas automáticos. É necessário implementar um Gatilho de Crise no ERP/WMS para casos que ultrapassem 30 dias de aging, com reporte direto à gerência.',
    'rel.rec3_title': 'Auditoria de Contratos e SLAs:',
    'rel.rec3_desc': ' É imperativo realizar uma revisão técnica nos contratos de transporte e operação logística para aplicar as cláusulas de penalidade por extravio ou atraso excessivo na logística reversa, visando recuperar o capital parado através de ressarcimento.',
    'rel.footer': 'Shopee Logistics Intelligence • Documento Confidencial',
    'rel.all': 'Todos: '
  },
  en: {
    'app.title': 'Shopee RTS Control Tower',
    'app.tab.operacional': 'Operational Dashboard',
    'app.tab.executiva': 'Executive View',
    'app.tab.relatorio': 'Strategic Report',
    'app.lastUpdate': 'Last update:',
    'app.loading': 'Loading data...',
    'app.error': 'Error loading data',
    'app.uploadCsv': 'Upload CSV',
    'app.tryAgain': 'Try Again',
    'app.corsError': 'Google Sheets blocked direct access due to CORS policies.',
    'app.corsSolution': 'To view the data, download the spreadsheet as a CSV and upload it below:',
    'app.downloadCsv': '1. Download CSV from Google Sheets',
    'app.selectFile': '2. Select downloaded file',
    
    'op.station': 'Station',
    'op.responsability': 'Responsibility',
    'op.stuckAging': 'Stuck Aging',
    'op.sinceDropAging': 'Since Drop Aging',
    'op.totalShipments': 'Total Shipments',
    'op.clickToViewAll': 'Click to view all',
    'op.avgDaysStation': 'Avg Days in Station',
    'op.days': 'days',
    'op.clickToViewAboveAvg': 'Click to view above average',
    'op.percentStuck': '% Stuck >5 days',
    'op.clickToViewCases': 'Click to view {count} cases',
    'op.critical20': 'Critical >20 days',
    'op.clickToDetailCritical': 'Click for critical details',
    'op.volByResp': 'Volume by Responsibility',
    'op.agingInStation': 'Aging in Station',
    'op.distRtsDays': 'RTS Days Distribution (Histogram)',
    'op.rtsMonitoring': 'RTS Monitoring',
    'op.shipmentId': 'Shipment ID',
    'op.daysInStation': 'Days in Station',
    'op.rtsDays': 'RTS Days',
    'op.stuckDays': 'Stuck Days',
    'op.noRecords': 'No records found.',
    'op.showing': 'Showing {start} to {end} of {total} records',
    'op.prev': 'Previous',
    'op.next': 'Next',
    'op.allShipments': 'All Shipments',
    'op.aboveAvg': 'Above Station Average (> {avg} days)',
    'op.stuck5': 'Stuck > 5 days',
    'op.criticalRts': 'Critical > 20 days (RTS)',
    'op.clearFilter': 'Clear KPI Filter',

    'exec.distRtsAging': 'RTS Aging Distribution',
    'exec.top10Critical': 'Top 10 Critical Stations (>10 days)',
    'exec.execSummary': 'EXECUTIVE SUMMARY',
    'exec.currentBase': 'Current base:',
    'exec.openShipments': 'open shipments',
    'exec.stuckMoreThan5': 'are stuck for more than 5 days',
    'exec.casesExceed20': 'cases exceed 20 days',
    'exec.recommendation': 'Immediate action is recommended for stations with an average of more than 10 days.',
    'exec.spxStatusVol': 'SPX Status (Volume)',
    'exec.spxStatusPct': 'SPX Status (%)',
    'exec.grandTotal': 'Grand Total',
    'exec.showMore': 'Show More ({count})',
    'exec.showLess': 'Show Less',
    'exec.topSpxStatus': 'The most frequent SPX status is',
    'exec.representing': 'representing',
    'exec.ofTotalVolume': 'of the total volume',

    'rel.filterOpType': 'Filter by Operation Type',
    'rel.searchOp': 'Search operation (e.g. SOC, HUB)...',
    'rel.noOpFound': 'No operation found',
    'rel.showingAll': 'Showing all operations.',
    'rel.stationsSelected': '{count} station(s) selected.',
    'rel.exportPdf': 'Export PDF',
    'rel.to': 'TO:',
    'rel.toValue': 'Operations Directorate / Supply Chain Management',
    'rel.from': 'FROM:',
    'rel.fromValue': 'Reverse Logistics Intelligence Engineering',
    'rel.subject': 'SUBJECT:',
    'rel.subjectValue': 'Strategic Performance and Asset Recovery Report',
    'rel.date': 'DATE:',
    'rel.sec1': '1. Executive Summary',
    'rel.p1_1': 'The current scenario of the reverse logistics operation ',
    'rel.p1_focus': '(focus on {tags}) ',
    'rel.p1_2': 'presents a state that requires immediate attention. With a volume of ',
    'rel.p1_3': ' items',
    'rel.p1_4': ' retained in the flow, operational inefficiency is evidenced by the Average Aging which reached ',
    'rel.p1_5': ' days',
    'rel.p1_6': ' of retention since RTS.',
    'rel.p2_1': 'The operation records ',
    'rel.p2_2': '% of SLA non-compliance',
    'rel.p2_3': ' (items over 30 days), and all of these items are classified as High Risk. These data indicate that the products are, in practice, paralyzed in the flow or retained due to severe bureaucratic/procedural issues, resulting in asset depreciation and high opportunity cost for the company.',
    'rel.sec2': '2. Technical Diagnosis',
    'rel.sec2_desc': 'The detailed analysis points to specific bottlenecks in the macro return process. The tables below detail the most critical locations and the responsible parties with the longest retention times.',
    'rel.analysisLoc': 'Analysis by Location (Regional Bottlenecks - Top 5)',
    'rel.location': 'Location',
    'rel.volItems': 'Volume (Items)',
    'rel.avgAgingDays': 'Average Aging (Days)',
    'rel.critStatus': 'Criticality Status',
    'rel.critical': 'Critical',
    'rel.warning': 'Warning',
    'rel.noData': 'No data to display',
    'rel.analysisResp': 'Analysis by Responsibility',
    'rel.analysisRespDesc': 'Responsibility is distributed, but the following sectors hold the longest retention times, indicating failures in the last mile of reverse logistics and inbound sorting.',
    'rel.responsible': 'Responsible',
    'rel.volume': 'Volume',
    'rel.processImpact': 'Process Impact',
    'rel.impact1': 'Failure in physical collection/return',
    'rel.impact2': 'Failure in checking/inventory',
    'rel.impact3': 'Delay in process/dispute',
    'rel.engObs': 'Engineering Observation:',
    'rel.engObsDesc': 'An aging of more than 30 days in a large part of the sample indicates that these items may have suffered unrecorded losses in the system or are in an administrative "limbo" between custody transfers.',
    'rel.analysisSpx': 'Analysis by SPX Status',
    'rel.analysisSpxDesc': 'The distribution of SPX statuses reveals the main systemic and operational bottlenecks in the reverse logistics flow.',
    'rel.spxStatus': 'SPX Status',
    'rel.spxPercentage': 'Representativeness',
    'rel.spxInsight': 'The {status} status concentrates most of the volume ({percentage}), requiring prioritization in systemic and physical unlocking.',
    'rel.sec3': '3. Practical Recommendations',
    'rel.sec3_desc': 'To reverse the stagnation and prevent further losses, the following actions must be taken immediately:',
    'rel.rec1_title': 'Sanitation Task Force (Write-off or Recovery):',
    'rel.rec1_desc': ' Due to the high aging, the probability of physical integrity of older items is low. I recommend immediate physical auditing in the most critical locations identified above. If the items are not located within 48h, proceed with write-off and activate insurance or penalize those responsible.',
    'rel.rec2_title': 'Escalation Flow Review:',
    'rel.rec2_desc': ' The fact that a significant portion of items is out of SLA and High Risk without prior intervention shows a failure in automatic alerts. It is necessary to implement a Crisis Trigger in the ERP/WMS for cases exceeding 30 days of aging, with direct reporting to management.',
    'rel.rec3_title': 'Contract and SLA Audit:',
    'rel.rec3_desc': ' It is imperative to conduct a technical review of transport and logistics operation contracts to apply penalty clauses for loss or excessive delay in reverse logistics, aiming to recover tied-up capital through reimbursement.',
    'rel.footer': 'Shopee Logistics Intelligence • Confidential Document',
    'rel.all': 'All: '
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key as keyof typeof translations['pt']] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
